### ISSUE TITLE
[FR] Allow writing to stdout

### ISSUE THREAD

**Issue by jessesimpson36** [jessesimpson36/yamldifftool#1]
**Describe the use case:**

most CLI projects will write to stdout by default and if specified, will write to a file.  In this tool, currently it writes to a file named `output` unless otherwise specified.

**Comment by mpa-LHutchinson** [comment]
Hi, can you assign this issue to me? I'll get working on it as soon as I can today. And if you don't mind, when I create the pull request later can you give it the "hacktoberfest-accepted" label?

**Comment by jessesimpson36** [comment]
Sounds good.

**Comment by mpa-LHutchinson** [comment]
@jessesimpson36 I updated this issue with #5

**Comment by jessesimpson36** [comment]
I've added the hacktoberfest-accepted label to both the issue and the PR. Let me know if theres anything I must do for you there.

**Comment by mpa-LHutchinson** [comment]
@jessesimpson36 the PR got accepted for hacktoberfest. Thank you!
